### ISSUE TITLE
Redirect Service Dockerfile is missing

### ISSUE THREAD

**Issue by surajraut362** [SevenProsHub/url-shortner#3]
![image](https://user-images.githubusercontent.com/31158685/218246970-3253b42b-c0de-4959-aff7-f85f28a6435f.png)
Docker file to build application is missing

**Comment by surajraut362** [comment]
![image](https://user-images.githubusercontent.com/31158685/218254997-dfedc50e-407f-4420-82bb-88046cea36d6.png)

Don't know but redirect app (go-lang) is failing two routine checks.
Then, Connected to DB-server.





![image](https://user-images.githubusercontent.com/31158685/218255112-816a0790-4e82-4f75-8946-f7ec323fc52d.png)
In docker-compose.yml, can find there is dependency of db(postgres) on redirect-service, but still getting two continuous error with db connection.
@AmitSureshChandra @dhiraj9022

**Comment by surajraut362** [comment]
Currently, I'm done with this enchancement issue you guys can check whether its a bug or natural behaviour of go-lang app.
According to situation take action.
@AmitSureshChandra @dhiraj9022

**Comment by AmitSureshChandra** [comment]
Seems good

**Comment by surajraut362** [comment]
Done with fix
